name: .NET API Automation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'   # use your project's .NET version

    - name: Restore dependencies
    run: dotnet restore TestAutomation.RestApi.csproj

    - name: Build
    run: dotnet build TestAutomation.RestApi.csproj --configuration Release

    - name: Run NUnit tests
    run: dotnet test TestAutomation.RestApi.csproj --configuration Release --logger "trx;LogFileName=test_results.trx"

